"""HPV vaccine metaregression project input and output paths"""
ROOT_DIR = FILEPATH

CLEANED_REG_DF = ROOT_DIR + FILEPATH
PAIRED_CWALK_DF = ROOT_DIR + FILEPATH

PLOT_DIR = ROOT_DIR + FILEPATH

CWALK_PARAM_SUMMARY = ROOT_DIR + FILEPATH
CWALK_PARAM_DRAWS = ROOT_DIR + FILEPATH

MODEL_RESULTS_DIR = ROOT_DIR + FILEPATH

CLEANED_PREDS_DF = ROOT_DIR + FILEPATH
